apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/jouw/github/repo
  branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./k8s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-app
  targetNamespace: test-app
